/*
 * Program: Pro Draft List
 * File: Add_Player_Main.java
 * Summary: Display main Add Player window of GUI for Pro Draft List
 * Author: Vincent Christaldi
 * Date: 01/14/18
*/
package pro_draft_list;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author Cruise McClarren
 */
public class Add_Player_Main extends javax.swing.JFrame
{

    private ArrayList Roster;

    /**
     * Creates new form Add_Player_Main
     */
    public Add_Player_Main()
    {
        initComponents();

        this.getContentPane().setBackground(Color.black);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());
    }

    public Add_Player_Main(ArrayList Roster)
    {
        initComponents();

        this.getContentPane().setBackground(Color.black);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_Main_Prompt = new java.awt.Label();
        rdb_Name = new javax.swing.JRadioButton();
        rdb_Position = new javax.swing.JRadioButton();
        btn_Previous = new java.awt.Button();
        btn_Next = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Player To Roster");
        setName("frm_Add_Player_Main"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        lbl_Main_Prompt.setAlignment(java.awt.Label.CENTER);
        lbl_Main_Prompt.setBackground(new java.awt.Color(51, 51, 255));
        lbl_Main_Prompt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_Main_Prompt.setForeground(new java.awt.Color(51, 0, 51));
        lbl_Main_Prompt.setText("How Would You Like To Choose A Player");

        buttonGroup1.add(rdb_Name);
        rdb_Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdb_Name.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Name.setSelected(true);
        rdb_Name.setText("Choose By Name");

        buttonGroup1.add(rdb_Position);
        rdb_Position.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdb_Position.setForeground(new java.awt.Color(255, 255, 255));
        rdb_Position.setText("Choose By Position");

        btn_Previous.setBackground(new java.awt.Color(255, 0, 0));
        btn_Previous.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        btn_Previous.setForeground(new java.awt.Color(0, 0, 51));
        btn_Previous.setLabel("Previous");
        btn_Previous.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_PreviousActionPerformed(evt);
            }
        });

        btn_Next.setBackground(new java.awt.Color(255, 255, 51));
        btn_Next.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        btn_Next.setForeground(new java.awt.Color(51, 0, 51));
        btn_Next.setLabel("Next Step");
        btn_Next.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Main_Prompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdb_Position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_Main_Prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdb_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Previous, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btn_Next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Exit_Window ex = new Exit_Window();
        this.dispose();
        ex.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_PreviousActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_PreviousActionPerformed
    {//GEN-HEADEREND:event_btn_PreviousActionPerformed
        Main_Window mw = new Main_Window();
        this.dispose();
        mw.setVisible(true);
    }//GEN-LAST:event_btn_PreviousActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_NextActionPerformed
    {//GEN-HEADEREND:event_btn_NextActionPerformed
        if (rdb_Name.isSelected() == true)
        {
            Pro_Draft_List pdl = new Pro_Draft_List(Roster);
            this.dispose();
            pdl.setVisible(true);
        }
        if (rdb_Position.isSelected() == true)
        {
            Position_Window pw = new Position_Window(Roster);
            this.dispose();
            pw.setVisible(true);
        }
    }//GEN-LAST:event_btn_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Add_Player_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Add_Player_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Add_Player_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Add_Player_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Add_Player_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_Next;
    private java.awt.Button btn_Previous;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Label lbl_Main_Prompt;
    private javax.swing.JRadioButton rdb_Name;
    private javax.swing.JRadioButton rdb_Position;
    // End of variables declaration//GEN-END:variables
}
