/*
 * Program: Pro Draft List
 * File: Main_Window.java
 * Summary: Display main window of GUI for Pro Draft List
 * Author: Vincent Christaldi
 * Date: 01/14/18
*/
package pro_draft_list;

import java.awt.*;
import javax.swing.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.io.File;
import java.util.*;

/**
 *
 * @author Cruise McClarren
 */
public class Main_Window extends javax.swing.JFrame
{
    File RosterFile;
   

//create roster file to store roster
        /**
     * Creates new form Main_Window
     */
    ArrayList<String> roster = new ArrayList<>();
    
    
    public Main_Window()
    {
        this.RosterFile = new File("Roster.txt");
        initComponents();
        this.getContentPane().setBackground(Color.green);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());
        if(RosterFile.exists() == false)
        {
            final Formatter RosterFile;
            try
            {
                RosterFile = new Formatter("Roster.txt");
            }
            catch(Exception e)
            {
                
            }
        }
    }
    public Main_Window(ArrayList Roster)
    {
        this.RosterFile = new File("Roster.txt");
        initComponents();
        this.getContentPane().setBackground(Color.green);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        lbl_MainPrompt = new java.awt.Label();
        rdb_AddPlayer = new javax.swing.JRadioButton();
        rdb_ViewRoster = new javax.swing.JRadioButton();
        btn_Exit = new java.awt.Button();
        btn_Proceed = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pro Draft List");
        setName("Main_Window"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        lbl_MainPrompt.setAlignment(java.awt.Label.CENTER);
        lbl_MainPrompt.setBackground(new java.awt.Color(0, 255, 255));
        lbl_MainPrompt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_MainPrompt.setForeground(new java.awt.Color(153, 0, 0));
        lbl_MainPrompt.setText("What would you like to do?");

        buttonGroup1.add(rdb_AddPlayer);
        rdb_AddPlayer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdb_AddPlayer.setForeground(new java.awt.Color(0, 0, 51));
        rdb_AddPlayer.setSelected(true);
        rdb_AddPlayer.setText("Add Player To Roster");

        buttonGroup1.add(rdb_ViewRoster);
        rdb_ViewRoster.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdb_ViewRoster.setForeground(new java.awt.Color(51, 0, 51));
        rdb_ViewRoster.setText("View Roster");
        rdb_ViewRoster.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdb_ViewRosterActionPerformed(evt);
            }
        });

        btn_Exit.setBackground(new java.awt.Color(255, 0, 0));
        btn_Exit.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        btn_Exit.setForeground(new java.awt.Color(0, 0, 51));
        btn_Exit.setLabel(" Exit Program");
        btn_Exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_Proceed.setBackground(new java.awt.Color(255, 255, 0));
        btn_Proceed.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        btn_Proceed.setForeground(new java.awt.Color(0, 0, 102));
        btn_Proceed.setLabel("Proceed");
        btn_Proceed.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_ProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdb_ViewRoster, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdb_AddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lbl_MainPrompt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_MainPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(rdb_AddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdb_ViewRoster, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Proceed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Exit_Window ex = new Exit_Window();
        this.dispose();
        ex.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_ExitActionPerformed
    {//GEN-HEADEREND:event_btn_ExitActionPerformed
        Exit_Window ex = new Exit_Window();
        this.dispose();
        ex.setVisible(true);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_ProceedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_ProceedActionPerformed
    {//GEN-HEADEREND:event_btn_ProceedActionPerformed
        if(rdb_AddPlayer.isSelected()== true)
        {
            Add_Player_Main apm = new Add_Player_Main(roster);
            this.dispose();
            apm.setVisible(true);
        }
        if(rdb_ViewRoster.isSelected()== true)
        {
            ViewRoster VR = new ViewRoster(roster);
            this.dispose();
            VR.setVisible(true);
        }
    }//GEN-LAST:event_btn_ProceedActionPerformed

    private void rdb_ViewRosterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdb_ViewRosterActionPerformed
    {//GEN-HEADEREND:event_rdb_ViewRosterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_ViewRosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                try
                {
                    Thread.sleep(2500);
                }
                catch(Exception e)
                {
                    
                }
                new Main_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_Exit;
    private java.awt.Button btn_Proceed;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private java.awt.Label lbl_MainPrompt;
    private javax.swing.JRadioButton rdb_AddPlayer;
    private javax.swing.JRadioButton rdb_ViewRoster;
    // End of variables declaration//GEN-END:variables
}
