/*
 * Program: Pro Draft List
 * File: Player_Stats_Window.java
 * Summary: Display Defensive Player Stats window of GUI for Pro Draft List
 * Author: Vincent Christaldi
 * Date: 01/14/18
*/
package pro_draft_list;

import java.awt.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.util.ArrayList;
import javax.swing.*;
import java.util.*;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Cruise McClarren
 */
public class Player_Stats_Window extends javax.swing.JFrame
{

    //ArrayList<String> Roster = new ArrayList<>();
    public ArrayList Roster;
    File RosterFile = new File("Roster.txt");

    /**
     * Creates new form Player_Stats_Window
     */
    public Player_Stats_Window()
    {
        initComponents();
        this.getContentPane().setBackground(Color.cyan);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());

    }

    public Player_Stats_Window(String Name, String position, String height, String age, String weight, String year, String tackles, String f_fumbles, String avg_Yards, String intcpts, String seasons)
    {
        initComponents();
        //lbl_PlayerName.setText(Name);
        this.getContentPane().setBackground(Color.cyan);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());
        lbl_PlayerName.setText(Name);
        lbl_DisplayPosition.setText(position);
        lbl_DisplayAge.setText(age);
        lbl_DisplayWeight.setText(weight);
        lbl_DisplayHeight.setText(height);
        lbl_DisplayAvgYards.setText(avg_Yards);
        lbl_DisplayTackles.setText(tackles);
        lbl_DisplayStartYear.setText(year);
        lbl_DisplaySeasonsPlayed.setText(seasons);
        lbl_DisplayForcedFumbles.setText(f_fumbles);
        lbl_DisplayInterceptions.setText(intcpts);

    }

    public Player_Stats_Window(String Name, String position, String height, String age, String weight, String year, String tackles, String f_fumbles, String avg_Yards, String intcpts, String seasons, ArrayList Roster)
    {
        initComponents();
        //lbl_PlayerName.setText(Name);
        this.getContentPane().setBackground(Color.cyan);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());
        lbl_PlayerName.setText(Name);
        lbl_DisplayPosition.setText(position);
        lbl_DisplayAge.setText(age);
        lbl_DisplayWeight.setText(weight);
        lbl_DisplayHeight.setText(height);
        lbl_DisplayAvgYards.setText(avg_Yards);
        lbl_DisplayTackles.setText(tackles);
        lbl_DisplayStartYear.setText(year);
        lbl_DisplaySeasonsPlayed.setText(seasons);
        lbl_DisplayForcedFumbles.setText(f_fumbles);
        lbl_DisplayInterceptions.setText(intcpts);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbl_PlayerName = new java.awt.Label();
        lbl_AgeLabel = new java.awt.Label();
        lbl_DisplayAge = new java.awt.Label();
        lbl_HeightLabel = new java.awt.Label();
        lbl_DisplayHeight = new java.awt.Label();
        lbl_WieghtLabel = new java.awt.Label();
        lbl_DisplayWeight = new java.awt.Label();
        lbl_PositionLabel = new java.awt.Label();
        lbl_DisplayPosition = new java.awt.Label();
        lbl_SeasonsPlayed = new java.awt.Label();
        lbl_DisplaySeasonsPlayed = new java.awt.Label();
        lbl_TacklesLabel = new java.awt.Label();
        lbl_DisplayTackles = new java.awt.Label();
        lbl_ForcedFumblesLabel = new java.awt.Label();
        lbl_DisplayForcedFumbles = new java.awt.Label();
        lbl_AvgYardsLabel = new java.awt.Label();
        lbl_DisplayAvgYards = new java.awt.Label();
        lbl_InterceptionsLabel = new java.awt.Label();
        lbl_DisplayInterceptions = new java.awt.Label();
        lbl_StartYearLabel = new java.awt.Label();
        lbl_DisplayStartYear = new java.awt.Label();
        btn_AddPlayer = new java.awt.Button();
        btn_Previous = new java.awt.Button();
        btn_MainMenu = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        lbl_PlayerName.setAlignment(java.awt.Label.CENTER);
        lbl_PlayerName.setBackground(java.awt.Color.cyan);
        lbl_PlayerName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_PlayerName.setText("Darius Slay");

        lbl_AgeLabel.setBackground(java.awt.Color.cyan);
        lbl_AgeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_AgeLabel.setText("Age:");

        lbl_DisplayAge.setBackground(java.awt.Color.cyan);
        lbl_DisplayAge.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayAge.setText("25");

        lbl_HeightLabel.setBackground(java.awt.Color.cyan);
        lbl_HeightLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_HeightLabel.setText("Height:");

        lbl_DisplayHeight.setBackground(java.awt.Color.cyan);
        lbl_DisplayHeight.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayHeight.setText("6' 1\"");

        lbl_WieghtLabel.setBackground(java.awt.Color.cyan);
        lbl_WieghtLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_WieghtLabel.setText("Weight:");

        lbl_DisplayWeight.setBackground(java.awt.Color.cyan);
        lbl_DisplayWeight.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayWeight.setText("255");

        lbl_PositionLabel.setBackground(java.awt.Color.cyan);
        lbl_PositionLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_PositionLabel.setText("Position:");

        lbl_DisplayPosition.setBackground(java.awt.Color.cyan);
        lbl_DisplayPosition.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayPosition.setText("Running Back");

        lbl_SeasonsPlayed.setBackground(java.awt.Color.cyan);
        lbl_SeasonsPlayed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_SeasonsPlayed.setText("Seasons Played:");

        lbl_DisplaySeasonsPlayed.setBackground(java.awt.Color.cyan);
        lbl_DisplaySeasonsPlayed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplaySeasonsPlayed.setText("4");

        lbl_TacklesLabel.setBackground(java.awt.Color.cyan);
        lbl_TacklesLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_TacklesLabel.setText("Tackles:");

        lbl_DisplayTackles.setBackground(java.awt.Color.cyan);
        lbl_DisplayTackles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayTackles.setText("5");

        lbl_ForcedFumblesLabel.setBackground(java.awt.Color.cyan);
        lbl_ForcedFumblesLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_ForcedFumblesLabel.setText("Forced Fumbles:");

        lbl_DisplayForcedFumbles.setBackground(java.awt.Color.cyan);
        lbl_DisplayForcedFumbles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayForcedFumbles.setText("2");

        lbl_AvgYardsLabel.setBackground(java.awt.Color.cyan);
        lbl_AvgYardsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_AvgYardsLabel.setText("Avg. Yards:");

        lbl_DisplayAvgYards.setBackground(java.awt.Color.cyan);
        lbl_DisplayAvgYards.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayAvgYards.setText("4.5");

        lbl_InterceptionsLabel.setBackground(java.awt.Color.cyan);
        lbl_InterceptionsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_InterceptionsLabel.setText("Interceptions:");

        lbl_DisplayInterceptions.setBackground(java.awt.Color.cyan);
        lbl_DisplayInterceptions.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayInterceptions.setText("1");

        lbl_StartYearLabel.setBackground(java.awt.Color.cyan);
        lbl_StartYearLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_StartYearLabel.setText("Starting Year:");

        lbl_DisplayStartYear.setBackground(java.awt.Color.cyan);
        lbl_DisplayStartYear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayStartYear.setText("2009");

        btn_AddPlayer.setBackground(new java.awt.Color(204, 0, 204));
        btn_AddPlayer.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btn_AddPlayer.setLabel("Add Player To Roster");
        btn_AddPlayer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_AddPlayerActionPerformed(evt);
            }
        });

        btn_Previous.setBackground(new java.awt.Color(255, 0, 0));
        btn_Previous.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btn_Previous.setForeground(new java.awt.Color(0, 0, 51));
        btn_Previous.setLabel("Select New Player");
        btn_Previous.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_PreviousActionPerformed(evt);
            }
        });

        btn_MainMenu.setBackground(new java.awt.Color(0, 255, 0));
        btn_MainMenu.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btn_MainMenu.setForeground(new java.awt.Color(51, 0, 51));
        btn_MainMenu.setLabel("Main Menu");
        btn_MainMenu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_MainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_AvgYardsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_TacklesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_HeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_PositionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_ForcedFumblesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_SeasonsPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_WieghtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_InterceptionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lbl_StartYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_DisplayStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DisplayWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DisplaySeasonsPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DisplayInterceptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DisplayForcedFumbles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lbl_DisplayAvgYards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_DisplayAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DisplayHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DisplayPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DisplayTackles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btn_AddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_StartYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_WieghtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_SeasonsPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ForcedFumblesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_InterceptionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_PositionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_HeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_TacklesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_AvgYardsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_DisplayWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_DisplaySeasonsPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33))
                                            .addComponent(lbl_DisplayForcedFumbles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_DisplayInterceptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_DisplayPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_DisplayAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_DisplayHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_DisplayTackles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_DisplayAvgYards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_AddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Exit_Window ex = new Exit_Window();
        this.dispose();
        ex.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_PreviousActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_PreviousActionPerformed
    {//GEN-HEADEREND:event_btn_PreviousActionPerformed

        Add_Player_Main ap = new Add_Player_Main();
        this.dispose();
        ap.setVisible(true);
    }//GEN-LAST:event_btn_PreviousActionPerformed

    private void btn_MainMenuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_MainMenuActionPerformed
    {//GEN-HEADEREND:event_btn_MainMenuActionPerformed
        Main_Window mw = new Main_Window();
        this.dispose();
        mw.setVisible(true);
    }//GEN-LAST:event_btn_MainMenuActionPerformed

    private void btn_AddPlayerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_AddPlayerActionPerformed
    {//GEN-HEADEREND:event_btn_AddPlayerActionPerformed
        String tempName = "";
        boolean okWrite = false;

        try
        {

            {
                FileWriter writeRoster = new FileWriter(RosterFile, true);
                BufferedWriter RosterBuffer = new BufferedWriter(writeRoster);
                PrintWriter printRoster = new PrintWriter(RosterBuffer);
                printRoster.println(lbl_PlayerName.getText());
                printRoster.close();
            }
        } catch (IOException ex)
        {
            Logger.getLogger(Player_Stats_Window.class.getName()).log(Level.SEVERE, null, ex);
        }

        ViewRoster vw = new ViewRoster();
        this.dispose();
        vw.setVisible(true);
    }//GEN-LAST:event_btn_AddPlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Player_Stats_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Player_Stats_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Player_Stats_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Player_Stats_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Player_Stats_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_AddPlayer;
    private java.awt.Button btn_MainMenu;
    private java.awt.Button btn_Previous;
    private java.awt.Label lbl_AgeLabel;
    private java.awt.Label lbl_AvgYardsLabel;
    private java.awt.Label lbl_DisplayAge;
    private java.awt.Label lbl_DisplayAvgYards;
    private java.awt.Label lbl_DisplayForcedFumbles;
    private java.awt.Label lbl_DisplayHeight;
    private java.awt.Label lbl_DisplayInterceptions;
    private java.awt.Label lbl_DisplayPosition;
    private java.awt.Label lbl_DisplaySeasonsPlayed;
    private java.awt.Label lbl_DisplayStartYear;
    private java.awt.Label lbl_DisplayTackles;
    private java.awt.Label lbl_DisplayWeight;
    private java.awt.Label lbl_ForcedFumblesLabel;
    private java.awt.Label lbl_HeightLabel;
    private java.awt.Label lbl_InterceptionsLabel;
    private java.awt.Label lbl_PlayerName;
    private java.awt.Label lbl_PositionLabel;
    private java.awt.Label lbl_SeasonsPlayed;
    private java.awt.Label lbl_StartYearLabel;
    private java.awt.Label lbl_TacklesLabel;
    private java.awt.Label lbl_WieghtLabel;
    // End of variables declaration//GEN-END:variables
}
