/*
 * Program: Pro Draft List
 * File: Player_Stats_Window1.java
 * Summary: Display Offensive Player Stats window of GUI for Pro Draft List
 * Author: Vincent Christaldi
 * Date: 01/14/18
*/
package pro_draft_list;

import java.awt.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Cruise McClarren
 */
public class Player_Stats_Window1 extends javax.swing.JFrame
{

    File RosterFile = new File("Roster.txt");

    /**
     * Creates new form Player_Stats_Window
     */
    public Player_Stats_Window1()
    {
        initComponents();
        this.getContentPane().setBackground(Color.cyan);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());

    }

    public Player_Stats_Window1(String PlayerName, String position, String height, String age, String weight, String avg_Yards, String tot_Carries, String totYards, String year, String RTG, String TDS, String incpts, String recpts, String seasons)
    {
        initComponents();
        lbl_PlayerName.setText(PlayerName);
        this.getContentPane().setBackground(Color.cyan);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());

        if (PlayerName == "Le'Veon Bell" || PlayerName == "Orleans Darkwa" || PlayerName == "Tom Brady" || PlayerName == "Antonio Brown" || PlayerName == "Kareem Hunt")
        {
            lbl_PlayerName.setText(PlayerName);
            lbl_DisplayPosition.setText(position);
            lbl_DisplayAge.setText(age);
            lbl_DisplayWeight.setText(weight);
            lbl_DisplayHeight.setText(height);
            lbl_DisplayAvgYards.setText(avg_Yards);
            lbl_DisplayTotCarries.setText(tot_Carries);
            lbl_DisplayTotYards.setText(totYards);
            lbl_DisplayStartYear.setText(year);
            lbl_DisplaySeasonsPlayed.setText(seasons);
            lbl_DisplayTouchdowns.setText(TDS);
            if (PlayerName == "Tom Brady")
            {
                lbl_AvgYardsLabel.setText("Interceptions:");
                lbl_TotCarriesLabel.setText("Runs To Goal:");
                lbl_DisplayAvgYards.setText(incpts);
                lbl_DisplayTotCarries.setText(RTG);
            }

        }

    }

    public Player_Stats_Window1(String PlayerName, String position, String height, String age, String weight, String avg_Yards, String tot_Carries, String totYards, String year, String RTG, String TDS, String incpts, String recpts, String seasons, ArrayList Roster)
    {
        initComponents();
        lbl_PlayerName.setText(PlayerName);
        this.getContentPane().setBackground(Color.cyan);
        //set icon image on title bar
        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());

        if (PlayerName == "Le'Veon Bell" || PlayerName == "Orleans Darkwa" || PlayerName == "Tom Brady" || PlayerName == "Antonio Brown" || PlayerName == "Kareem Hunt")
        {
            lbl_PlayerName.setText(PlayerName);
            lbl_DisplayPosition.setText(position);
            lbl_DisplayAge.setText(age);
            lbl_DisplayWeight.setText(weight);
            lbl_DisplayHeight.setText(height);
            lbl_DisplayAvgYards.setText(avg_Yards);
            lbl_DisplayTotCarries.setText(tot_Carries);
            lbl_DisplayTotYards.setText(totYards);
            lbl_DisplayStartYear.setText(year);
            lbl_DisplaySeasonsPlayed.setText(seasons);
            lbl_DisplayTouchdowns.setText(TDS);
            if (PlayerName == "Tom Brady")
            {
                lbl_AvgYardsLabel.setText("Interceptions:");
                lbl_TotCarriesLabel.setText("Runs To Goal:");
                lbl_DisplayAvgYards.setText(incpts);
                lbl_DisplayTotCarries.setText(RTG);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbl_PlayerName = new java.awt.Label();
        lbl_AgeLabel = new java.awt.Label();
        lbl_DisplayAge = new java.awt.Label();
        lbl_HeightLabel = new java.awt.Label();
        lbl_DisplayHeight = new java.awt.Label();
        lbl_WieghtLabel = new java.awt.Label();
        lbl_DisplayWeight = new java.awt.Label();
        lbl_PositionLabel = new java.awt.Label();
        lbl_DisplayPosition = new java.awt.Label();
        lbl_SeasonsPlayed = new java.awt.Label();
        lbl_DisplaySeasonsPlayed = new java.awt.Label();
        lbl_TotYardsLabel = new java.awt.Label();
        lbl_DisplayTotYards = new java.awt.Label();
        lbl_TotCarriesLabel = new java.awt.Label();
        lbl_DisplayTotCarries = new java.awt.Label();
        lbl_AvgYardsLabel = new java.awt.Label();
        lbl_DisplayAvgYards = new java.awt.Label();
        lbl_TouchdownsLabel = new java.awt.Label();
        lbl_DisplayTouchdowns = new java.awt.Label();
        lbl_StartYearLabel = new java.awt.Label();
        lbl_DisplayStartYear = new java.awt.Label();
        btn_AddPlayer = new java.awt.Button();
        btn_Previous = new java.awt.Button();
        btn_MainMenu = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Player Stats");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        lbl_PlayerName.setAlignment(java.awt.Label.CENTER);
        lbl_PlayerName.setBackground(java.awt.Color.cyan);
        lbl_PlayerName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_PlayerName.setText("Darius Slay");

        lbl_AgeLabel.setBackground(java.awt.Color.cyan);
        lbl_AgeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_AgeLabel.setText("Age:");

        lbl_DisplayAge.setBackground(java.awt.Color.cyan);
        lbl_DisplayAge.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayAge.setText("25");

        lbl_HeightLabel.setBackground(java.awt.Color.cyan);
        lbl_HeightLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_HeightLabel.setText("Height:");

        lbl_DisplayHeight.setBackground(java.awt.Color.cyan);
        lbl_DisplayHeight.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayHeight.setText("6' 1\"");

        lbl_WieghtLabel.setBackground(java.awt.Color.cyan);
        lbl_WieghtLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_WieghtLabel.setText("Weight:");

        lbl_DisplayWeight.setBackground(java.awt.Color.cyan);
        lbl_DisplayWeight.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayWeight.setText("255");

        lbl_PositionLabel.setBackground(java.awt.Color.cyan);
        lbl_PositionLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_PositionLabel.setText("Position:");

        lbl_DisplayPosition.setBackground(java.awt.Color.cyan);
        lbl_DisplayPosition.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayPosition.setText("Running Back");

        lbl_SeasonsPlayed.setBackground(java.awt.Color.cyan);
        lbl_SeasonsPlayed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_SeasonsPlayed.setText("Seasons Played:");

        lbl_DisplaySeasonsPlayed.setBackground(java.awt.Color.cyan);
        lbl_DisplaySeasonsPlayed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplaySeasonsPlayed.setText("4");

        lbl_TotYardsLabel.setBackground(java.awt.Color.cyan);
        lbl_TotYardsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_TotYardsLabel.setText("Total Yards:");

        lbl_DisplayTotYards.setBackground(java.awt.Color.cyan);
        lbl_DisplayTotYards.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayTotYards.setText("5");

        lbl_TotCarriesLabel.setBackground(java.awt.Color.cyan);
        lbl_TotCarriesLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_TotCarriesLabel.setText("Total Carries:");

        lbl_DisplayTotCarries.setBackground(java.awt.Color.cyan);
        lbl_DisplayTotCarries.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayTotCarries.setText("2");

        lbl_AvgYardsLabel.setBackground(java.awt.Color.cyan);
        lbl_AvgYardsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_AvgYardsLabel.setText("Avg. Yards:");

        lbl_DisplayAvgYards.setBackground(java.awt.Color.cyan);
        lbl_DisplayAvgYards.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayAvgYards.setText("4.5");

        lbl_TouchdownsLabel.setBackground(java.awt.Color.cyan);
        lbl_TouchdownsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_TouchdownsLabel.setText("Touchdowns:");

        lbl_DisplayTouchdowns.setBackground(java.awt.Color.cyan);
        lbl_DisplayTouchdowns.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayTouchdowns.setText("1");

        lbl_StartYearLabel.setBackground(java.awt.Color.cyan);
        lbl_StartYearLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_StartYearLabel.setText("Starting Year:");

        lbl_DisplayStartYear.setBackground(java.awt.Color.cyan);
        lbl_DisplayStartYear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_DisplayStartYear.setText("2009");

        btn_AddPlayer.setBackground(new java.awt.Color(204, 0, 204));
        btn_AddPlayer.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btn_AddPlayer.setLabel("Add Player To Roster");
        btn_AddPlayer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_AddPlayerActionPerformed(evt);
            }
        });

        btn_Previous.setBackground(new java.awt.Color(255, 0, 0));
        btn_Previous.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btn_Previous.setForeground(new java.awt.Color(0, 0, 51));
        btn_Previous.setLabel("Select New Player");
        btn_Previous.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_PreviousActionPerformed(evt);
            }
        });

        btn_MainMenu.setBackground(new java.awt.Color(0, 255, 0));
        btn_MainMenu.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btn_MainMenu.setForeground(new java.awt.Color(51, 0, 51));
        btn_MainMenu.setLabel("Main Menu");
        btn_MainMenu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_MainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_HeightLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_TotYardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_AgeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_PositionLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_AvgYardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_DisplayPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayTotYards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayAvgYards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_TotCarriesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_SeasonsPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_WieghtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_TouchdownsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lbl_StartYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_DisplayStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplaySeasonsPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayTouchdowns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayTotCarries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lbl_PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btn_AddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_StartYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_WieghtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_SeasonsPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_TotCarriesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_TouchdownsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_PositionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_AgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_HeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(lbl_AvgYardsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_DisplayWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_DisplaySeasonsPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33))
                                            .addComponent(lbl_DisplayTotCarries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_DisplayTouchdowns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_DisplayPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_DisplayAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_DisplayHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_TotYardsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DisplayTotYards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_DisplayAvgYards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_AddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Exit_Window ex = new Exit_Window();
        this.dispose();
        ex.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_MainMenuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_MainMenuActionPerformed
    {//GEN-HEADEREND:event_btn_MainMenuActionPerformed
        Main_Window mw = new Main_Window();
        this.dispose();
        mw.setVisible(true);
    }//GEN-LAST:event_btn_MainMenuActionPerformed

    private void btn_PreviousActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_PreviousActionPerformed
    {//GEN-HEADEREND:event_btn_PreviousActionPerformed
        Add_Player_Main ap = new Add_Player_Main();
        this.dispose();
        ap.setVisible(true);
    }//GEN-LAST:event_btn_PreviousActionPerformed

    private void btn_AddPlayerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_AddPlayerActionPerformed
    {//GEN-HEADEREND:event_btn_AddPlayerActionPerformed

        try
        {

            FileWriter writeRoster = new FileWriter(RosterFile, true);
            BufferedWriter RosterBuffer = new BufferedWriter(writeRoster);
            PrintWriter printRoster = new PrintWriter(RosterBuffer);
            printRoster.println(lbl_PlayerName.getText());
            printRoster.close();

        } catch (IOException ex)
        {

        }

        ViewRoster vw = new ViewRoster();
        this.dispose();
        vw.setVisible(true);
    }//GEN-LAST:event_btn_AddPlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Player_Stats_Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Player_Stats_Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Player_Stats_Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Player_Stats_Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Player_Stats_Window1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_AddPlayer;
    private java.awt.Button btn_MainMenu;
    private java.awt.Button btn_Previous;
    private java.awt.Label lbl_AgeLabel;
    private java.awt.Label lbl_AvgYardsLabel;
    private java.awt.Label lbl_DisplayAge;
    private java.awt.Label lbl_DisplayAvgYards;
    private java.awt.Label lbl_DisplayHeight;
    private java.awt.Label lbl_DisplayPosition;
    private java.awt.Label lbl_DisplaySeasonsPlayed;
    private java.awt.Label lbl_DisplayStartYear;
    private java.awt.Label lbl_DisplayTotCarries;
    private java.awt.Label lbl_DisplayTotYards;
    private java.awt.Label lbl_DisplayTouchdowns;
    private java.awt.Label lbl_DisplayWeight;
    private java.awt.Label lbl_HeightLabel;
    private java.awt.Label lbl_PlayerName;
    private java.awt.Label lbl_PositionLabel;
    private java.awt.Label lbl_SeasonsPlayed;
    private java.awt.Label lbl_StartYearLabel;
    private java.awt.Label lbl_TotCarriesLabel;
    private java.awt.Label lbl_TotYardsLabel;
    private java.awt.Label lbl_TouchdownsLabel;
    private java.awt.Label lbl_WieghtLabel;
    // End of variables declaration//GEN-END:variables
}
