/*
 * Program: Pro Draft List
 * File: Position_Window.java
 * Summary: Display Select Position Window of GUI for Pro Draft List
 * Author: Vincent Christaldi
 * Date: 01/14/18
*/
package pro_draft_list;

import java.awt.Color;
import java.util.ArrayList;


/**
 *
 * @author Cruise McClarren
 */
public class Position_Window extends javax.swing.JFrame
{

    private ArrayList Roster;

    /**
     * Creates new form Position_Window
     */
    public Position_Window()
    {
        initComponents();
        this.getContentPane().setBackground(Color.magenta);
    }
    public Position_Window(ArrayList Roster)
    {
        initComponents();
        this.getContentPane().setBackground(Color.magenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rdb_Offense = new javax.swing.JRadioButton();
        rdb_Defense = new javax.swing.JRadioButton();
        btn_Exit = new java.awt.Button();
        btn_Main = new java.awt.Button();
        btn_Next = new java.awt.Button();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        rdb_Offense.setBackground(java.awt.Color.magenta);
        buttonGroup1.add(rdb_Offense);
        rdb_Offense.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        rdb_Offense.setSelected(true);
        rdb_Offense.setText("Choose By Offense");

        rdb_Defense.setBackground(java.awt.Color.magenta);
        buttonGroup1.add(rdb_Defense);
        rdb_Defense.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        rdb_Defense.setText("Choose By Defense");

        btn_Exit.setBackground(new java.awt.Color(204, 0, 0));
        btn_Exit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_Exit.setLabel("Exit Program");
        btn_Exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_ExitActionPerformed(evt);
            }
        });

        btn_Main.setBackground(new java.awt.Color(0, 255, 255));
        btn_Main.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_Main.setLabel("Main Menu");
        btn_Main.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_MainActionPerformed(evt);
            }
        });

        btn_Next.setBackground(new java.awt.Color(0, 255, 51));
        btn_Next.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_Next.setLabel("Next");
        btn_Next.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_NextActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(java.awt.Color.magenta);
        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setText("Select Position");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btn_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdb_Defense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdb_Offense, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdb_Offense)
                .addGap(37, 37, 37)
                .addComponent(rdb_Defense)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btn_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_ExitActionPerformed
    {//GEN-HEADEREND:event_btn_ExitActionPerformed
        Exit_Window ew = new Exit_Window();
        this.dispose();
        ew.setVisible(true);
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Exit_Window ew = new Exit_Window();
        this.dispose();
        ew.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_MainActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_MainActionPerformed
    {//GEN-HEADEREND:event_btn_MainActionPerformed
        Main_Window mw = new Main_Window();
        this.dispose();
        mw.setVisible(true);
    }//GEN-LAST:event_btn_MainActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_NextActionPerformed
    {//GEN-HEADEREND:event_btn_NextActionPerformed
        
        if(rdb_Offense.isSelected()==true)
        {
            
            
            OffensePosition OPW = new OffensePosition(Roster);
            this.dispose();
            OPW.setVisible(true);
            
        }
        else
        {
        DefensePosition DPW = new DefensePosition(Roster);
        this.dispose();
        DPW.setVisible(true);
        }
    }//GEN-LAST:event_btn_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Position_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Position_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Position_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Position_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Position_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_Exit;
    private java.awt.Button btn_Main;
    private java.awt.Button btn_Next;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Label label1;
    private javax.swing.JRadioButton rdb_Defense;
    private javax.swing.JRadioButton rdb_Offense;
    // End of variables declaration//GEN-END:variables
}
