/*
 * Program: Pro Draft List
 * File: ViewRoster.java
 * Summary: Display View Roster of GUI for Pro Draft List
 * Author: Vincent Christaldi
 * Date: 01/14/18
*/
package pro_draft_list;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Cruise McClarren
 */
public class ViewRoster extends javax.swing.JFrame
{

    public ArrayList Roster;
    public String[] RosterArray = new String[9];
    //private Scanner rdFile;

    /**
     * Creates new form ViewRoster
     */
    public ViewRoster(ArrayList Roster)
    {
        initComponents();
        this.getContentPane().setBackground(Color.yellow);

        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());
        try
        {
            BufferedReader rdFile = new BufferedReader(new FileReader("Roster.txt"));
            String PlyrName = "";
            int tempIndx = 1;
            while ((PlyrName = rdFile.readLine()) != null)
            {
                if (PlyrName != lst_Roster.getItem(tempIndx))
                {
                    lst_Roster.add(PlyrName);
                }
            }
            rdFile.close();
        } catch (Exception e)
        {

        }

    }

    public ViewRoster()
    {
        initComponents();
        this.getContentPane().setBackground(Color.yellow);

        setIconImage(new ImageIcon(getClass().getResource("/images/PDLIcon.png")).getImage());
        try
        {
            BufferedReader rdFile = new BufferedReader(new FileReader("Roster.txt"));
            String PlyrName = "";

            while ((PlyrName = rdFile.readLine()) != null)
            {
                lst_Roster.add(PlyrName);
            }
            rdFile.close();
        } catch (Exception e)
        {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbl_Header = new java.awt.Label();
        lbl_curRoster = new java.awt.Label();
        btnAddPlyr = new java.awt.Button();
        btnRemove = new java.awt.Button();
        btnClose = new java.awt.Button();
        btn_MainWindow = new java.awt.Button();
        lst_Roster = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        lbl_Header.setAlignment(java.awt.Label.CENTER);
        lbl_Header.setBackground(java.awt.Color.yellow);
        lbl_Header.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_Header.setText("View / Manage Current Roster");

        lbl_curRoster.setAlignment(java.awt.Label.CENTER);
        lbl_curRoster.setBackground(java.awt.Color.yellow);
        lbl_curRoster.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_curRoster.setText("::::Current Roster::::");

        btnAddPlyr.setBackground(new java.awt.Color(0, 255, 0));
        btnAddPlyr.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAddPlyr.setLabel("<<ADD PLAYER");
        btnAddPlyr.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddPlyrActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(153, 0, 153));
        btnRemove.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnRemove.setLabel(">>REMOVE PLAYER");
        btnRemove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoveActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        btnClose.setLabel("Exit Program");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        btn_MainWindow.setBackground(new java.awt.Color(51, 255, 255));
        btn_MainWindow.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        btn_MainWindow.setLabel("Main Window");
        btn_MainWindow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_MainWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddPlyr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Header, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_MainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_curRoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lst_Roster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnAddPlyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_curRoster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lst_Roster, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_MainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        File Roster = new File("Roster.txt");
        Roster.delete();
        Exit_Window ex = new Exit_Window();
        this.dispose();
        ex.setVisible(true);

    }//GEN-LAST:event_formWindowClosing

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        File Roster = new File("Roster.txt");
        Roster.delete();
        Exit_Window ex = new Exit_Window();
        this.dispose();
        ex.setVisible(true);

    }//GEN-LAST:event_btnCloseActionPerformed

    private void btn_MainWindowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_MainWindowActionPerformed
    {//GEN-HEADEREND:event_btn_MainWindowActionPerformed

        Main_Window mw = new Main_Window(Roster);
        this.dispose();
        mw.setVisible(true);
    }//GEN-LAST:event_btn_MainWindowActionPerformed

    private void btnAddPlyrActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddPlyrActionPerformed
    {//GEN-HEADEREND:event_btnAddPlyrActionPerformed
        Add_Player_Main apm = new Add_Player_Main(Roster);
        this.dispose();
        apm.setVisible(true);
    }//GEN-LAST:event_btnAddPlyrActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemoveActionPerformed
    {//GEN-HEADEREND:event_btnRemoveActionPerformed
        ArrayList<String> tempList = new ArrayList<>();
        String removeName = lst_Roster.getSelectedItem();
        String name = "";
        tempList.clear();
        for (int index = 0; index < lst_Roster.getItemCount(); index++)
        {
            if(removeName != lst_Roster.getItem(index))
            {
                tempList.add(lst_Roster.getItem(index));
            }
            
        }
        lst_Roster.removeAll();
        try
        {

            BufferedWriter writeRoster = new BufferedWriter(new FileWriter("Roster.txt"));
            for (String x : tempList)
            {
                writeRoster.write(x);
                writeRoster.newLine();
            }
            writeRoster.close();
        } catch (Exception e)
        {

        }
        try
        {
            BufferedReader rdFile = new BufferedReader(new FileReader("Roster.txt"));
            String PlyrName = "";

            while ((PlyrName = rdFile.readLine()) != null)
            {
                lst_Roster.add(PlyrName);
            }
            rdFile.close();
        } catch (Exception e)
        {

        }


    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ViewRoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ViewRoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ViewRoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ViewRoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ViewRoster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAddPlyr;
    private java.awt.Button btnClose;
    private java.awt.Button btnRemove;
    private java.awt.Button btn_MainWindow;
    private java.awt.Label lbl_Header;
    private java.awt.Label lbl_curRoster;
    private java.awt.List lst_Roster;
    // End of variables declaration//GEN-END:variables
}
